name: Online_Judge
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - aiofiles=25.1.0
  - aiosqlite=0.21.0
  - annotated-types=0.7.0
  - anyio=4.10.0
  - arq=0.26.1
  - async-timeout=5.0.1
  - asyncpg=0.30.0
  - bcrypt=4.3.0
  - bzip2=1.0.8
  - ca-certificates=2025.11.12
  - certifi=2025.11.12
  - click=8.2.1
  - dnspython=2.7.0
  - email-validator=2.2.0
  - email_validator=2.2.0
  - exceptiongroup=1.3.0
  - fastapi=0.116.1
  - fastapi-cache2=0.2.2
  - fastapi-cli=0.0.8
  - fastapi-core=0.116.1
  - h11=0.16.0
  - h2=4.2.0
  - hiredis=3.2.1
  - hpack=4.1.0
  - httpcore=1.0.9
  - httptools=0.6.4
  - httpx=0.28.1
  - hyperframe=6.1.0
  - idna=3.10
  - importlib-metadata=6.10.0
  - iso8601=2.1.0
  - jinja2=3.1.6
  - ld_impl_linux-64=2.44
  - libffi=3.4.6
  - libgcc=15.1.0
  - libgcc-ng=15.1.0
  - libgomp=15.1.0
  - liblzma=5.8.1
  - liblzma-devel=5.8.1
  - libnsl=2.0.1
  - libsqlite=3.50.4
  - libuuid=2.38.1
  - libuv=1.51.0
  - libxcrypt=4.4.36
  - libzlib=1.3.1
  - markdown-it-py=4.0.0
  - markupsafe=3.0.2
  - mdurl=0.1.2
  - ncurses=6.5
  - openssl=3.6.0
  - pendulum=3.1.0
  - pip=25.2
  - psutil=7.1.0
  - pydantic=2.11.7
  - pydantic-core=2.33.2
  - pygments=2.19.2
  - pypika-tortoise=0.6.1
  - python=3.10.13
  - python-dateutil=2.9.0.post0
  - python-dotenv=1.1.1
  - python-multipart=0.0.20
  - python_abi=3.10
  - pytz=2025.2
  - pyyaml=6.0.2
  - readline=8.2
  - redis-py=4.6.0
  - rich=14.1.0
  - rich-toolkit=0.15.0
  - setuptools=80.9.0
  - shellingham=1.5.4
  - six=1.17.0
  - sniffio=1.3.1
  - starlette=0.47.2
  - time-machine=2.19.0
  - tk=8.6.13
  - tomlkit=0.13.3
  - tortoise-orm=0.25.1
  - typer=0.16.1
  - typer-slim=0.16.1
  - typer-slim-standard=0.16.1
  - typing-extensions=4.14.1
  - typing-inspection=0.4.1
  - typing_extensions=4.14.1
  - tzdata=2025b
  - uvicorn=0.35.0
  - uvicorn-standard=0.35.0
  - uvloop=0.21.0
  - watchfiles=1.1.0
  - websockets=15.0.1
  - wheel=0.45.1
  - xz=5.8.1
  - xz-gpl-tools=5.8.1
  - xz-tools=5.8.1
  - yaml=0.2.5
  - zipp=3.23.0
  - pip:
      - aerich==0.9.1
      - aiodocker==0.24.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.12.15
      - aiosignal==1.4.0
      - asyncclick==8.1.8.0
      - attrs==25.3.0
      - charset-normalizer==3.4.3
      - dictdiffer==0.9.0
      - ecdsa==0.19.1
      - frozenlist==1.7.0
      - multidict==6.6.4
      - propcache==0.3.2
      - pyasn1==0.6.1
      - python-jose==3.5.0
      - requests==2.32.5
      - rsa==4.9.1
      - urllib3==2.5.0
      - yarl==1.20.1
